# Generated by Django 4.0.5 on 2022-08-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0030_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteoeconomia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.AddField(
            model_name='posteoespectaculos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.AddField(
            model_name='posteoultimasnoticias',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
