# Generated by Django 4.0.5 on 2022-08-15 22:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0031_posteoeconomia_foto_posteoespectaculos_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteoeconomia',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='posteoespectaculos',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
